-- MySQL Script generated by MySQL Workbench
-- Thu May  2 09:51:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `forum`;

USE `forum`;

-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`Questions` ;

CREATE TABLE IF NOT EXISTS `forum`.`Questions` (
  `questionsID` INT NOT NULL,
  `universityStatus` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `questionTitle` VARCHAR(45) NULL,
  `postText` TEXT NULL,
  PRIMARY KEY (`questionsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forum`.`Answers` ;

CREATE TABLE IF NOT EXISTS `forum`.`Answers` (
  `answerID` INT NOT NULL,
  `answer` TEXT NULL,
  `questionsID` INT NOT NULL,
  PRIMARY KEY (`answerID`),
  INDEX `fk_Answers_Questions1_idx` (`questionsID` ASC) VISIBLE,
  CONSTRAINT `fk_Answers_Questions1`
    FOREIGN KEY (`questionsID`)
    REFERENCES `mydb`.`Questions` (`questionsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


